### test
GET http://localhost:8090/api/v0/users/test

### test 404

GET http://localhost:8090/api/v0/sdfsdfsd

### signup

POST http://localhost:8090/api/v0/auth/signup
content-type: application/json

{
  "email": "fahmi@ed.com",
  "password": "something",
  "passwordConfirmation": "something",
  "type": "nonSubscriber",
  "demo": true
}

### login

POST http://localhost:8090/api/v0/auth/login
content-type: application/json

{
  "email": "fahmi@ed.com",
  "password": "something"
}

### logout

GET http://localhost:8090/api/v0/auth/logout

### admin login

POST http://localhost:8090/api/v0/auth/login-admin
content-type: application/json

{
  "email": "someone@something.com",
  "password": "password"
}