### test
GET http://localhost:8090/api/v0/users/test

### test 404

GET http://localhost:8090/api/v0/sdfsdfsd

### signup

POST http://localhost:8090/api/v0/auth/signup
content-type: application/json

{
  "email": "fahmi@ed.com",
  "password": "something",
  "passwordConfirmation": "something",
  "type": "nonSubscriber",
  "demo": true
}

### login

POST http://localhost:8090/api/v0/auth/login
content-type: application/json

{
  "email": "fahmi@ed.com",
  "password": "something"
}

### logout

GET http://localhost:8090/api/v0/auth/logout

#############################################
#                 ADMIN                     #
#############################################

### admin login

POST http://localhost:8090/api/v0/admin/login
content-type: application/json

{
  "email": "fahmi@backoffice.com",
  "password": "something88888"
}

### admin logout
GET http://localhost:8090/api/v0/admin/logout
content-type: application/json
Authorization: token aaa

### admin refresh
POST http://localhost:8090/api/v0/admin/refresh-token
Content-Type: application/json

{
  "refresh_token": "aaa"
}

### create todo
POST http://localhost:8090/api/v0/todo/create
Content-Type: application/json
Authorization: token aaa

{
  "title": "Test jwt"
}

### admin CRUD ###
##################
POST http://localhost:8090/api/v0/admin/crud/create-admin
content-type: application/json
Authorization: token aaa

{
  "email": "fahmi@backoffice.com",
  "password": "something88888",
  "passwordConfirmation": "something88888",
  "role": "admin"
}